version: "3.3"

services:
  postgres:
    image: postgres
    restart: always
    expose:
      - "5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin123
      # - POSTGRES_HOST_AUTH_METHOD=trust
  redis:
    image: redis:latest
    restart: always
    expose:
      - 6379
  web:
    restart: always
    build: .
    env_file:
      - .env.local
    command: bash -c "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000 "
    volumes:
      - ".:/app"
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
  celery:
    build: .
    env_file:
      - .env.local
    command: celery -A abanerd_django worker -l info
    volumes:
      - .:/app
    depends_on:
      - web
      - redis
  celery-beat:
    build: .
    env_file:
      - .env.local
    command: celery -A abanerd_django beat -l info
    volumes:
      - .:/app
    depends_on:
      - web
      - redis
