version: "3.3"

services:
  redis:
    image: redis:latest
    restart: always
    expose:
      - 6379
  web:
    build: .
    env_file:
      - .env.local
    command: sh -c "python manage.py collectstatic --no-input &&
                    python manage.py migrate &&
                    python manage.py loaddata data/static.json &&
                    gunicorn --worker-class gevent --log-level debug abanerd_django.wsgi -b 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - redis
  celery:
    build: .
    env_file:
      - .env.local
    command: celery -A abanerd_django worker -l info
    volumes:
      - .:/code
    depends_on:
      - web
      - redis
  celery-beat:
    build: .
    env_file:
      - .env.local
    command: celery -A abanerd_django beat -l info
    volumes:
      - .:/code
    depends_on:
      - web
      - redis
