version: "3.9"

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  redis:
    image: redis:latest
    restart: always
    expose:
      - 6379
  web:
    build: .
    env_file:
      - .env.dev
    command: sh -c "python manage.py collectstatic --no-input &&
                    python manage.py migrate &&
                    make migrateall &&
                    gunicorn --worker-class gevent --log-level debug abanerd_django.wsgi -b 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
  celery:
    build: .
    env_file:
      - .env.dev
    command: celery -A abanerd_django worker -l info
    volumes:
      - .:/code
    depends_on:
      - web
      - redis
  celery-beat:
    build: .
    env_file:
      - .env.dev
    command: celery -A abanerd_django beat -l info
    volumes:
      - .:/code
    depends_on:
      - web
      - redis
