# Generated by Django 3.1.3 on 2021-02-14 23:23

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import stdimage.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CEUCreditType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True)),
                ('slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='name', unique_with=('name',))),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CEUImageFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('filename', models.TextField(default='none', max_length=256)),
                ('image_url', models.CharField(default=None, max_length=512, null=True, unique=True)),
                ('image', stdimage.models.StdImageField(blank=True, upload_to='ceu-image')),
            ],
        ),
        migrations.CreateModel(
            name='CEUMediaType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True)),
                ('slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='name', unique_with=('name',))),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CEUSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('url', models.URLField(max_length=250)),
                ('slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='name', unique_with=('created', 'modified', 'url'))),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('url', models.URLField(blank=True, max_length=250, null=True)),
                ('slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='name', unique_with=('created', 'modified', 'url'))),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CSVFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('file', models.FileField(upload_to='csv-data-upload-files/')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='abanerd.provider')),
            ],
        ),
        migrations.CreateModel(
            name='CEUCredit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('published_date', models.DateTimeField(blank=True)),
                ('title', models.CharField(max_length=1024, unique=True)),
                ('description', models.TextField()),
                ('url', models.URLField(max_length=2048)),
                ('image_url', models.CharField(blank=True, default=None, max_length=512)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('credits', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('event_date', models.DateTimeField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='title', unique_with=('provider', 'title'))),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ceu_image', to='abanerd.ceuimagefile')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ceu_media_type', to='abanerd.ceumediatype')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ceu_provider', to='abanerd.provider')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ceu_credit_type', to='abanerd.ceucredittype')),
            ],
            options={
                'ordering': ['title'],
                'unique_together': {('provider', 'title')},
            },
        ),
    ]
